### ISSUE TITLE
findTracking line feeds cause missed detection

### ISSUE THREAD

**Issue by 0xA-10** [rjbrooksjr/ts-tracking-number#14]
First off, awesome work and thank you for posting this module.

It seems that findTracking has some trouble with linefeeds (\n).

Fail:
`http://www.fedex.com/Tracking?ascend_header=1&clienttype=dotcom&cntry_code=us&language=english&tracknumbers=254899580324\n254899580324`

`254899580324\n254899580324`

Pass:
`http://www.fedex.com/Tracking?ascend_header=1&clienttype=dotcom&cntry_code=us&language=english&tracknumbers=254899580324`

`http://www.fedex.com/Tracking?ascend_header=1&clienttype=dotcom&cntry_code=us&language=english&tracknumbers=254899580324\nfoo254899580324`

While testing, I also noticed the following:

`254899580\n254899580324`

Will detect the FedEx SmartPost number "254899580254899580324", i.e. it is not respecting the line break between the numbers. Moreover, it won't detect the 254899580324 FedEx Express number within it. This design is fine, I am just pointing out how the line breaks do not seem to be maintained and/or accounted for during pattern matching.

I am mitigating this by replacing linefeeds with _ in my searchText.

**Comment by rjbrooksjr** [comment]
That's a great write up, thank you. I'll take a look at it.

**Comment by rjbrooksjr** [comment]
This should be fixed now in version 1.0.13. Let me know if you have any additional problems. Thanks!
