### ISSUE TITLE
Ontrac has expanded the range of codes they use

### ISSUE THREAD

**Issue by rorcores** [rjbrooksjr/ts-tracking-number#21]
Hey there,

Ontrac now use a wider range of codes. I've updated it for you and lodged a PR here,

https://github.com/rjbrooksjr/ts-tracking-number/pull/20

Thanks,
Rory

**Comment by rjbrooksjr** [comment]
Hey, somehow I completely missed this. Sorry about that. I'll take a look and get this merged in. Thanks!

**Comment by rorcores** [comment]
no worries

**Comment by rjbrooksjr** [comment]
Merged and published one month later. I am the worst.
